### ISSUE TITLE
Mina, kui arendaja, soovin andmebaasi initsialiseerimise skripti, et andmeid manuaalselt mitte sisestada.

### ISSUE THREAD

**Issue by OooJee** [vikreinok/tks#1]
St et schemad luuakse nii nagu ma ise olen täpselt ette andnud ning rakendus ei teeks ise midagi juurde. Samuti ei tohiks rakendus AB maha kustutada rakenduse sulgemisl. 
Võiks olla andmebaasi versiooni haldus.

**Comment by vikreinok** [comment]
catering-core/src/main/resources/import.sql

**Comment by OooJee** [comment]
Põhimõtteliselt sobib aga hetkel esinevad kodeeringu probleemid. Täpitähed st (Ö, Ä, Õ, Ü ) on veidrate tähtedega. Fixida ennem see

**Comment by vikreinok** [comment]
Proovi:

CREATE DATABASE catering_menu CHARACTER SET utf8 COLLATE utf8_general_ci;;
GRANT ALL PRIVILEGES ON *.* TO 'catering_menu'@'localhost';

**Comment by vikreinok** [comment]
Tehtud. 
Probleem MYSQL Admin ida.
