### ISSUE TITLE
Mina, kui arendaja, tahan, et projekti haldus vahendis oleks kirjeldatud tööprotsess.

### ISSUE THREAD

**Issue by vikreinok** [vikreinok/tks#12]
Loo wikisse uus leht kus on kirjledautd meie tööprotsess mis oleks sünkroonis ainega projekti juhtimine.

Vt. loegnu saide ja nõudeid.

Näide: 
Näiteks luua uus staatus "Story". Mõned sttatused eemaldada. Staatuste kasutamise reeglistik jne.

**Comment by vikreinok** [comment]
IS projekti juhtimise aine slidide 5 ja 6 seest leiab palju selle teemaga sotud inffi.

**Comment by otttt** [comment]
Kirjeldatud wikis.
