### ISSUE TITLE
Mina, kui arendaja, soovin et, kommentaar lisatakse dineri põhiselt

### ISSUE THREAD

**Issue by OooJee** [vikreinok/tks#14]
Hetkel käib kommentaaride lisamine vastu menüüd, kuigi see pole päris adekvaatne. Tegelikult peaks vastu dinerit kommentaaride lisamine käima

**Comment by vikreinok** [comment]
Kommentaari lisamine dinerile:
POST  /diner/comment/{dinerId}   Post sisus DinerComment object.

Menu kommentaari lisamine alles.

**Comment by OooJee** [comment]
Tegin kommentaari vormi ära mobiilii poole peale ja testisin. Saan ainult ühe kommentaari lisada  ja siis teise lisamisel tuleb Internal Server Error. Logisid ei vaadanud Tomcat poolel, kuid ilmselt on sama asi, mis Hajusarhitektuuri aine kommentaari lisamisel see bug tuli. Võiks kuidagi selle fixida.
