### ISSUE TITLE
Mina, kui arendaja, soovin et back endis luuakse uus andmebaasitabel Users

### ISSUE THREAD

**Issue by OooJee** [vikreinok/tks#15]
Oleks vaja uut andmebaasi tabelit, mis talletaks informatsiooni registreeritud kasutajate kohta. Eelkõige tuleks seal hoida andmeid nagu kasutajanimi, parool, e-mail ja tema lemmikud dinerid.

**Comment by OooJee** [comment]
Mis seis sellega siis on?

**Comment by otttt** [comment]
Tegime teistmoodi lahenduse.
