### ISSUE TITLE
Mina kui arendaja, soovin et oleks teenus, mis dineri põhiselt tagastaks ainult selle dineri kommentaarid

### ISSUE THREAD

**Issue by OooJee** [vikreinok/tks#22]
Praegu saaks kommentaare kätte nt sellise URL-ga: http://imbi.ld.ttu.ee:443/catering-core/rest/diner/1

See aga annab vastuseks ka muud infot peale kommentaaride. Vaja oleks aga sellist teenust, mis annab konkreetselt vastuseks dineriga seotud kommentaarid.

**Comment by otttt** [comment]
Tehtud!
