### ISSUE TITLE
Mina, kui arendaja, soovin paremat git repo nime, et see kirjeldaks seda projekti.

### ISSUE THREAD

**Issue by vikreinok** [vikreinok/tks#3]
Mõelda midagi uut ja arusaadavamt võrreldes tks-iga.

**Comment by otttt** [comment]
Uue repositooriumi nime võimalikud variandid: Diners, eDiner, iDiner, TTÜ Diners, DineSys
Samamoodi võiks see olla ka äpi nimi.
