### ISSUE TITLE
Mina, kui arendaja, pean nägema süsteemi arhetektuuri setsifiktasiooni, et saada ülevaade süsteemist.

### ISSUE THREAD

**Issue by vikreinok** [vikreinok/tks#4]
Tee eraldi kaust  repo juurikasse ja pane sinna kausta doc arhetektuurist mis sai valmis Hajus Arh aine korras.

**Comment by otttt** [comment]
Korras, lõin kausta Documentation ja lisasin sinna faili hajusdok2.docx
